## Question: Which Vancouver sports team should you cheer for? üèí

It's no secret that most of us reading this are bandwagoners - but fear not! If we are going to embrace bandwagoning, we should obviously turn our attention to the team that has the best win percentage. In Vancouver, there are six professional sports teams that battle at the highest level amongst their respective leagues. These leagues range from football to soccer to baseball and even to gaming. The question is: **Which professional sports team in Vancouver has the best win percentage throughout the years? Which team should I cheer for year-to-year that gives me the best chance to do my victory dance?**

Professional Sports Teams in Vancouver:
* BC Lions (American Football)
* Vancouver Canadians (Baseball)
* Vancouver Canucks (Ice Hockey)
* Vancouver Titans (Overwatch/Gaming)
* Vancouver Warriors (Lacrosse)
* Vancouver Whitecaps (Soccer)

In [79]:
# invite the party people!
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [80]:
# write a helper function to assist in transforming wiki tables into dataframes
def get_df(url,pos):
    res = requests.get(url)
    soup = BeautifulSoup(res.content,'lxml')
    table = soup.find_all('table')[pos] 
    df = pd.read_html(str(table))[0]
    return df

In [201]:
# Let's start with the BC Lions
df_lions = get_df('https://en.wikipedia.org/wiki/List_of_BC_Lions_seasons',1)
# lets clean this up a bit and extract only the relevant information
df_lions = df_lions.iloc[0:64]
# filter out for the columns we want (win/loss)
df_lions_col = ['Leagueseason', 'Wins', 'Losses']
df_lions = df_lions[df_lions_col]
# calculate the win percentage for ever year as an additional column
df_lions['Win Percentage'] = (df_lions['Wins'] / (df_lions['Wins'] + df_lions['Losses']))*100
# rename Leagueseason to season
df_lions.rename(columns={"Leagueseason": "Season"},inplace=True)
# convert entire dataframe to numbers
df_lions = df_lions.apply(pd.to_numeric)
#df_lions.info()
df_lions.head()

   Season  Wins  Losses  Win Percentage
0    1954     1      15        6.250000
1    1955     5      11       31.250000
2    1956     6      10       37.500000
3    1957     4      11       26.666667
4    1958     3      13       18.750000

In [364]:
# Vancouver Canadians is the only table that does not exist in Wikipedia. Table scraping should be similar though.
df_canadians = get_df('https://www.baseball-reference.com/bullpen/Vancouver_Canadians',0)
# Filter for relevant columns and drop 2019 with no data
df_canadians = df_canadians[['Year', 'Record']][:-1]
# Split the Record column into Wins and Losses
df_canadians[['Wins','Losses']] = df_canadians['Record'].str.split('-',expand=True) 
# Drop the Record column
df_canadians.drop(['Record'],inplace=True,axis=1)
print(df_canadians)
# Convert everything to a number
df_canadians["Wins"] = df_canadians["Wins"].astype(int)
df_canadians["Losses"] = df_canadians["Losses"].astype(int)
print(df_canadians)
# Calculate the win percentage
df_canadians['Win Percentage'] = ( df_canadians['Wins'] / (df_canadians['Wins'] + df_canadians['Losses']) )*100
# Rename Year to Season
df_canadians.rename(columns={"Year": "Season"},inplace=True)
df_canadians.info()

    Year Wins Losses
0   1978   74     65
1   1979   79     68
2   1980   79     60
3   1981   56     76
4   1982   72     72
5   1983   60     80
6   1984   71     71
7   1985   79     64
8   1986   85     53
9   1987   72     72
10  1988   85     57
11  1989   73     69
12  1990   74     67
13  1991   49     86
14  1992   81     61
15  1993   72     68
16  1994   77     65
17  1995   81     60
18  1996   68     70
19  1997   75     68
20  1998   53     90
21  1999   84     58
22  2000   39     37
23  2001   37     39
24  2002   37     39
25  2003   35     41
26  2004   42     34
27  2005   46     30
28  2006   39     37
29  2007   37     38
30  2008   34     42
31  2009   36     40
32  2010   42     34
33  2011   39     37
34  2012   46     30
35  2013   39     37
36  2014   46     30
37  2015   34     42
38  2016   29     45
39  2017   34     33
40  2018   40     36
    Year  Wins  Losses
0   1978    74      65
1   1979    79      68
2   1980    79      60
3   1981    56      76
4   1982    72      72
5   1983    60      80
6   1984    71      71
7   1985    79      64
8   1986    85      53
9   1987    72      72
10  1988    85      57
11  1989    73      69
12  1990    74      67
13  1991    49      86
14  1992    81      61
15  1993    72      68
16  1994    77      65
17  1995    81      60
18  1996    68      70
19  1997    75      68
20  1998    53      90
21  1999    84      58
22  2000    39      37
23  2001    37      39
24  2002    37      39
25  2003    35      41
26  2004    42      34
27  2005    46      30
28  2006    39      37
29  2007    37      38
30  2008    34      42
31  2009    36      40
32  2010    42      34
33  2011    39      37
34  2012    46      30
35  2013    39      37
36  2014    46      30
37  2015    34      42
38  2016    29      45
39  2017    34      33
40  2018    40      36
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
Season            41 non-null int64
Wins              41 non-null int32
Losses            41 non-null int32
Win Percentage    41 non-null float64
dtypes: float64(1), int32(2), int64(1)
memory usage: 1.0 KB

In [202]:
# Do the same for the Canucks
df_canucks = get_df('https://en.wikipedia.org/wiki/List_of_Vancouver_Canucks_seasons',2)
# Clean up and filter
df_canucks.columns = [' '.join(set(col)).strip() for col in df_canucks.columns.values]
df_canucks = df_canucks[['NHL season','W Regular-season', 'L Regular-season','W Postseason', 'L Postseason']]
# remove the year of the NHL Lockout
df_canucks.drop(df.index[34],inplace=True)
# convert undefined values in Postseason to 0
df_canucks['W Postseason'].replace('‚Äî', 0,inplace=True)
df_canucks['L Postseason'].replace('‚Äî', 0,inplace=True)
# remove non-digit values in Regular season
df_canucks['W Regular-season'] = df_canucks['W Regular-season'].str.extract('(\d+)', expand=False)
df_canucks['L Regular-season'] = df_canucks['L Regular-season'].str.extract('(\d+)', expand=False)
df_canucks['NHL season'] = df_canucks['NHL season'].str.extract('(\d+)', expand=False)
# convert entire dataframe to numbers
df_canucks = df_canucks.apply(pd.to_numeric)
# combine regular season and post seasons wins and losses
df_canucks['Wins'] = df_canucks['W Regular-season'] + df_canucks['W Postseason']
df_canucks['Losses'] = df_canucks['L Regular-season'] + df_canucks['L Postseason']
# calculate the win percentage for ever year as an additional column
df_canucks['Win Percentage'] = ( df_canucks['Wins'] / (df_canucks['Wins'] + df_canucks['Losses']) )*100
# rename NHL season to season
df_canucks.rename(columns={"NHL season": "Season"},inplace=True)
# only keep relevant columns
df_canucks = df_canucks[['Season','Wins','Losses','Win Percentage']]
#df_canucks.info()
df_canucks.head()

   Season  Wins  Losses  Win Percentage
0    1970    24      46       34.285714
1    1971    20      50       28.571429
2    1972    22      47       31.884058
3    1973    24      43       35.820896
4    1974    39      36       52.000000

In [311]:
# Lets create the dataframe for the Vancouver Titans
df_titans = get_df('https://en.wikipedia.org/wiki/2019_Vancouver_Titans_season',3)
# The Vancouver titans have only been playing for a single year, hence their table is spread across the games that occured in 2019
# First, let's extract out the 'Overall' row for the relevant data of the single year of play in 2019
df_titans = df_titans.iloc[5]
# Let's add a season column
df_titans['Season'] = 2019
# only keeping the relevant columns
df_titans = df_titans[['Season','W','L']]
# convert all columns to correct types
df_titans['Season'] = int(df_titans['Season'])
df_titans['W'] = int(df_titans['W'])
df_titans['L'] = int(df_titans['L'])
# Calculate the win percentage
df_titans['Win Percentage'] = ( df_titans['W'] / (df_titans['W'] + df_titans['L']) )*100
# Rename to correct column names
df_titans.rename({'W':'Wins','L':'Losses'},inplace=True)
df_titans

Season               2019
Wins                   24
Losses                  3
Win Percentage    88.8889
Name: 5, dtype: object

In [325]:
# Vancouver Warriors dataframe, let's go!
df_warriors = get_df('https://en.wikipedia.org/wiki/Vancouver_Warriors',2)
# This dataframe is interesting because its Win-Loss is in one column, we will need to parse this
# Let's get the relevant columns and remove the "Total" rows
df_warriors = df_warriors[['Season','W‚ÄìL']][:5]
# Split the W-L column into Wins and Losses
df_warriors[['Wins','Losses']] = df_warriors['W‚ÄìL'].str.split('‚Äì',expand=True) 
# Drop the W-L column
df_warriors.drop(['W‚ÄìL'],inplace=True,axis=1)
# Convert everything to a number
df_warriors = df_warriors.apply(pd.to_numeric)
# Calculate the win percentage
df_warriors['Win Percentage'] = ( df_warriors['Wins'] / (df_warriors['Wins'] + df_warriors['Losses']) )*100
df_warriors.head()

   Season  Wins  Losses  Win Percentage
0    2014     4      14       22.222222
1    2015     5      13       27.777778
2    2016     5      13       27.777778
3    2017     9       9       50.000000
4    2018     2      16       11.111111